src/web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace x.account.Models
{
    public class LoginViewModel
    {
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [Display(Name = "记住我?")]
        public bool RememberMe { get; set; }
    }
}

src/web/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace x.account.Models
{
    public class RegisterViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "{0} 必须至少包含 {2} 个字符。", MinimumLength = 6)]
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "{0} 必须至少包含 {2} 个字符。", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "确认密码")]
        [Compare("Password", ErrorMessage = "密码和确认密码不匹配。")]
        public string ConfirmPassword { get; set; }
    }
}

src/web/Models/SiteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace x.account.Models
{
    public class SiteViewModel
    {
        [Display(Name = "网址")]
        public string Site { get; set; }

        [Display(Name = "网站名称")]
        public string WebName { get; set; }
    }
    public class SiteEditViewModel : SiteViewModel
    {
        public string Id { get; set; }
    }
}

src/web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using x.account.Models;
using x.account.Utility;
using x.domain;
using x.domain.Entities;

namespace x.account.Controllers
{
    [Authorize]
    public class AccountController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (string.IsNullOrWhiteSpace(returnUrl))
                {
                    return RedirectToAction("index", "home");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            else
            {
                ViewBag.ReturnUrl = returnUrl;
                return View();
            }
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // 这不会计入到为执行帐户锁定而统计的登录失败次数中
            // 若要在多次输入错误密码的情况下触发帐户锁定，请更改为 shouldLockout: true
            var result = OwinService.SignIn(model.UserName, model.Password, model.RememberMe);
            switch (result)
            {
                case SignInResult.Success:
                    return RedirectToLocal(returnUrl);
                case SignInResult.LockedOut:
                    return View("Lockout");
                case SignInResult.UserNameError:
                    ModelState.AddModelError("", "用户名不存在");
                    return View(model);
                case SignInResult.PasswordError:
                    ModelState.AddModelError("", "密码不正确");
                    return View(model);
                default:
                    return View(model);
            }
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel model)
        {
            return RedirectToLocal(model, () =>
            {
                using (var context = new XAccountContext())
                {
                    var entity = new xt_user
                    {
                        id = Guid.NewGuid().ToString(),
                        access_failed_times = 0,
                        username = model.UserName
                    };
                    entity.password = new PasswordHasher().HashPassword(model.Password);
                    context.Add(entity);
                    context.SaveChanges();
                }
            }, "/Account/Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            OwinService.SignOut();
            return RedirectToAction("Login", "Account");
        }
    }
}

src/web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using x.account.Utility;

namespace x.account.Controllers
{
    public class BaseController : Controller
    {
        private IOWinService _oWinService;
        protected IOWinService OwinService => _oWinService ?? (_oWinService = new OWinService());

        public string LoginId => User.GetLoginId();

        protected ActionResult RedirectToLocal(string returnUrl)
        {
            if (returnUrl != null)
            {
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
        protected ActionResult RedirectToLocal<T>(T model, Action action, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                action();
                return RedirectToLocal(returnUrl);
            }
            return View(model);
        }

        private string GetModelStateString()
        {
            return string.Join("<br/>", ModelState.Select(o => o.Value).SelectMany(o => o.Errors).Select(o => o.ErrorMessage + o.Exception?.Message));
        }
    }
}

src/web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using x.account.Models;
using x.domain;
using x.domain.Entities;

namespace x.account.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            using (var context = new XAccountContext { LoginId = LoginId })
            {
                var list = context.AsNoTracking<xt_web>().Where(o => o.xt_user != null && o.xt_user.id == LoginId).OrderBy(o=>o.created_time).ToList();
                var viewModel = list.Select(o => new SiteEditViewModel
                {
                    Id = o.id,
                    Site = o.site,
                    WebName = o.web_name
                }).ToList();
                return View(viewModel);
            }
                
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/web/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using x.account.Models;
using x.domain;
using x.domain.Entities;

namespace x.account.Controllers
{
    [Authorize]
    public class SiteController : BaseController
    {
        // GET: Site
        public ActionResult AddSite()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSite(SiteViewModel model)
        {
            return RedirectToLocal(model, () =>
            {
                using (var context = new XAccountContext { LoginId = LoginId })
                {
                    var entity = new xt_web
                    {
                        id = Guid.NewGuid().ToString(),
                        site = model.Site,
                        web_name = model.WebName,
                        xt_user = context.xt_user.Find(LoginId)
                    };
                    context.Add(entity);
                    context.SaveChanges();
                }
            }, "/Home/Index");
        }
    }
}

src/web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<SiteEditViewModel >
<style>
    .panel-body {
        padding-bottom:0;
        padding-top:0;
    }
    .show-grid {
        margin-bottom: 0;
        height:43px;
    }
    .show-grid [class^="col-"]:first-child {
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .show-grid [class^="col-"] {
        background-color: #eee;
        background-color: rgba(86,61,124,.15);
        border: 1px solid #ddd;
        border: 1px solid rgba(86,61,124,.2);
        height: inherit;
    }
    .panel-group {
        margin-bottom: 8px;
    }
    .panel-group:last-child {
        margin-bottom:0;
    }
    .my-col-justified {
        padding: 0;
    }
    .my-col-justified > button {
        padding: 0;
        border: 0;
        height: 100%;
        width: 100%;
    }
</style>
<div class="panel panel-primary">
    @*<div class="panel-heading">
        <h3 class="panel-title">百度</h3>
    </div>*@
    <div class="panel-body">
        <div class="panel-group">
            <div class="row">
                <button type="button" class="btn btn-primary btn-block" onclick="window.location.href = '/Site/AddSite';">新增</button>
            </div>
            @foreach (var m in Model)
            {
                <div class="row show-grid">
                    <div class="col-xs-8"><a href="@m.Site">@m.WebName</a></div>
                    <div class="col-xs-2 my-col-justified">
                        <button type="button" class="btn btn-link btn4edit">Edit</button>
                    </div>
                    <div class="col-xs-2 my-col-justified">
                        <button type="button" class="btn btn-link">Copy</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

src/web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <style>
        .my-navbar-on .my-navbar-label {
            color: #09BB07;
        }
        .my-navbar-label {
            margin-bottom: 0;
        }
    </style>
</head>
<body style="background-color:#fff">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderBody()
    <!--网站、我-->
    <nav class="navbar navbar-default navbar-fixed-bottom my-navbar">
        <div class="btn-group btn-group-justified" role="group">
            <div class="btn-group my-navbar-item my-navbar-on" role="group">
                <button type="button" class="btn" style="padding:5px 0 0;border:0;border-radius: 0;" data-redirect="/home/index">
                    <img src="~/Images/icon_tabbar.png" style="width: 27px; height: 27px;"/>
                    <p class="my-navbar-label" style="height:20px;">网站</p>
                </button>
            </div>
            <div class="btn-group my-navbar-item" role="group" id="my-navbar-item-account">
                <button type="button" class="btn" style="padding:5px 0 0;border:0;border-radius: 0;" data-redirect="/account/index">
                    <img src="~/Images/icon_tabbar.png" style="width: 27px; height: 27px;" />
                    <p class="my-navbar-label" style="height:20px;">我</p>
                </button>
            </div>
        </div>
    </nav>
    @RenderSection("scripts", required: false)
    <script>
        $('.my-navbar-item').on('click', function () {
            
            $(this).addClass('my-navbar-on').siblings('.my-navbar-on').removeClass('my-navbar-on');

            window.location.href = $(this).find("button").data("redirect");
        });
    </script>
</body>
</html>

src/web/Views/Site/AddSite.cshtml
@{
    ViewBag.Title = "新增网站";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SiteViewModel
<div class="container myContainer">
    @using (Html.BeginForm("AddSite", "Site", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Site, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Site, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WebName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.WebName, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="提交" />
            </div>
        </div>
    }
</div>